{
 "title": "ADSB Ingest Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Events Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    { "expr": "rate(aw_adsb_total[1m])" }
   ]
  },
  {
   "title": "ADSB Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aw_adsb_total" }
   ]
  },
  {
   "title": "ADSB Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aw_adsb_err_total" }
   ]
  },
  {
   "title": "Catch",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aw_adsb_catch_total" }
   ]
  },
  {
   "title": "ADSB_Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aw_adsb_ADSB_Unknown_total" }
   ]
  },
  {
   "title": "ADSB_AirborneVelocity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_AirborneVelocity_total"
    }
   ]
  },
  {
   "title": "ADSB_AirbornePositionGNSS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_AirbornePositionGNSS_total"
    }
   ]
  },
  {
   "title": "ADSB_AirbornePositionBaro",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_AirbornePositionBaro_total"
    }
   ]
  },
  {
   "title": "ADSB_AircraftIdentification",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_AircraftIdentification_total"
    }
   ]
  },
  {
   "title": "ADSB_SurfacePosition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_SurfacePosition_total"
    }
   ]
  },
  {
   "title": "ADSB_AircraftStatus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_AircraftStatus_total"
    }
   ]
  },
  {
   "title": "ADSB_AircraftOperationStatus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aw_adsb_ADSB_AircraftOperationStatus_total"
    }
   ]
  },
  {
   "title": "ADSB_TargetState",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aw_adsb_ADSB_TargetState_total" }
   ]
  }
 ]
}